#game.language = en
window.width = 1280
window.height = 720
window.vsync = false

#ANGLE IN DEGREES
game.graphics.fov = 67
game.graphics.ui.font = Arial
game.graphics.ui.font_type = 0
game.graphics.ui.scale = 1

game.controls.forward = 87
game.controls.back = 83
game.controls.left = 65
game.controls.right = 68
game.controls.up = 32
game.controls.down = 340
game.controls.mouse_sensitivity = 0.2
game.controls.dev_menu = 292
